name = "swiftpdf"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "./"

[env.production]
name = "swiftpdf-prod"

[vars]
GEMINI_API_KEY = ""

[assets]
directory = "./dist"
