name = "swiftpdf"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.{ts,tsx}", "lib/**/*.ts", "*.tsx", "*.css"]

[env.production]
name = "swiftpdf-prod"

[vars]
GEMINI_API_KEY = ""
